### ISSUE TITLE
Voiceover issues umbrella

### ISSUE THREAD

**Issue by mozzius** [mozzius/graysky#120]
- [ ] Voiceover is completely broken (see other issue) introduced between build 196 and build 200 (toast?)
- [ ] Open drawer button not labelled as such
- [ ] 24m in notification is announced as 24 meters
- [ ] Feeds are not labelled as such and alt text on image just means it says the feed name twice. Also should say if favourited
- [ ] Forgot? -> Forgot password?
